export const GET_AVAILABLE_CURRENCIES = "GET_AVAILABLE_CURRENCIES";
export const GET_AVAILABLE_CURRENCIES_FAILED =
  "GET_AVAILABLE_CURRENCIES_FAILED";
export const SET_CHOSEN_CURRENCY = "SET_CHOSEN_CURRENCY";
export const SET_CHOSEN_CURRENCY_FAILED = "SET_CHOSEN_CURRENCY_FAILED";
export const SET_IS_SELECTOR_OPEN = "SET_IS_SELECTOR_OPEN";
export const CONVERT_CURRENCY = "CONVERT_CURRENCY";
export const CONVERT_CURRENCY_FAILED = "CONVERT_CURRENCY_FAILED";
export const SET_EXCHANGE_RATE = "SET_EXCHANGE_RATE";
export const SET_EXCHANGE_RATE_FAILED = "SET_EXCHANGE_RATE_FAILED";
